### ISSUE TITLE
Report control blocks not attaching trigger options or optional fields

### ISSUE THREAD

**Issue by IanYoung77** [transpower-nz/open-scd#30] opened 2024-11-29 01:26 UTC
When I add a report control block the save under the options doesn't seem to work. Whenever I change and enter data nothing happens. When I then change the RCB it resets them all giving and error. If I edit the saved SCD and add these options then open the project it is ok

**Comment by danyill** [comment] 2024-11-29 03:07
I can reproduce -- it looks like this functionality is not implemented yet, sorry.

**Comment by IanYoung77** [comment] 2024-11-29 03:10
Thanks danyill.

I was asked to look at the tool at the CIGRE meeting and was playing with the functionality. The GOOSE seemed to work ok. Haven't tried SV yet

Regards,
Ian YOUNG
____________________________________________________________________________________________________________

Ian YOUNG   |    Schneider Electric   |   Energy Business   |   Australia   |   Applications Manager
Phone: +61 2 9125 9373   |   Mobile: +61 419 698 801
Email: ***@***.******@***.***>   |   Site: www. schneider-electric.com/au   |   Address: 50 Stennett Road, Ingleburn NSW 2565 AUSTRALIA
*** Please consider the environment before printing this e-mail



General

**Comment by danyill** [comment] 2024-11-29 03:25
> Thanks danyill. I was asked to look at the tool at the CIGRE meeting and was playing with the functionality. The GOOSE seemed to work ok. Haven't tried SV yet 

All good - please log as many issues as you can find 😉

**Comment by danyill** [comment] 2024-12-02 09:08
I believe this is available now.

To refresh, suggest pressing Ctrl + F5.

Thanks for reporting, please re-open if it is not fixed.

**Comment by IanYoung77** [comment] 2024-12-02 10:23
It now adds the options but puts TrgOps after OptFields which it reports as invalid. I don't have a reopen option I can find

**Comment by danyill** [comment] 2024-12-02 17:32
Yes, I see that it depends on the order of options, let me look into that.

**Comment by IanYoung77** [comment] 2024-12-03 07:13
If you add the items in the right order it works. But you have to add the Trigger Options first, followed by Optional Fields then lastly add the max clients

**Comment by danyill** [comment] 2024-12-03 07:17
Yes, it will be fixed soon, just waiting for the fix to be reviewed. Thanks
for the update 👍

**Comment by danyill** [comment] 2024-12-03 17:53
I'm fairly sure it's correct now.

A hard refresh (Ctrl + F5) should give you the latest version. Thanks for all the feedback.

**Closed as completed by danyill** 2024-12-03 17:53 UTC
